language: node_js
node_js:
    - "12"
dist: trusty
addons:
    chrome: stable
    sonarcloud:
        organization: "adrianofelisberto"
branches:
  only:
    - master
    - develop
before_script:
  - npm install -g --silent @angular/cli
script:
  - ng lint
  - npm run test
  - npm run sonar
  - npm run build

skip_cleanup: true
on:
  branch: master

deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_ACCESS_TOKEN
  dir: dist
  edge: true