language: node_js
node_js:
    - "12"
dist: trusty
sudo: required
addons:
    chrome: stable
    sonarcloud:
        organization: "adrianofelisberto"
branches:
  only:
    - master
    - develop
before_script:
  - npm install -g --silent @angular/cli
script:
  - ng lint
  - npm run test
  - npm run sonar