name: primeiro-workflow
on:
  push:
    branches:
      - master
      - develop
jobs:
  npm-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          npm install
          npm run build
          npm test
  sonar-publish:
    runs-on: ubuntu-latest
    needs: npm-job
    steps:
      - name: Publish Sonar
        run: npm run sonar